#!/usr/bin/ruby
# encoding: utf-8
# (c) 2011 Martin Kozák (martinkozak@martinkozak.net)

$:.push("./lib")
$:.unshift("./lib")

require "em-jack"
require "unified-queues"
require "em-batch"

EM::run do
    q = UnifiedQueues::Multi::new(EMJack::Connection)
    
    queue = EM::Sequencer::new(q)
    queue.use(:xxx)
    queue.push("x", 2)
    queue.push("y", 1)
    queue.subscribe(:xxx)
    
    queue.execute do
        queue = EM::Sequencer::new(q)
        queue.pop
        queue.pop
        queue.pop
          
        queue.execute do
            p queue.results
            
            #q.pop 
        end
    end
end
