#!/usr/bin/ruby
# encoding: utf-8
# (c) 2011 Martin Kozák (martinkozak@martinkozak.net)

$:.push("./lib")
$:.unshift("./lib")

require "depq"
require "universal-queues"

q = UniversalQueues::Multi::new(UniversalQueues::Single, Depq)
q.use(:xxx)
q.push("x", 2)
q.push("y", 1)

q.subscribe(:xxx)
p q.pop
p q.pop

p q
