# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "unified-queues"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Koz\u{e1}k"]
  s.date = "2012-05-24"
  s.email = "martinkozak@martinkozak.net"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "CHANGES.txt",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "debug",
    "lib/unified-queues.rb",
    "lib/unified-queues/multi.rb",
    "lib/unified-queues/multi/driver.rb",
    "lib/unified-queues/multi/driver/em-jack.rb",
    "lib/unified-queues/multi/driver/unified-queues.rb",
    "lib/unified-queues/single.rb",
    "lib/unified-queues/single/driver.rb",
    "lib/unified-queues/single/driver/algorithms.rb",
    "lib/unified-queues/single/driver/array.rb",
    "lib/unified-queues/single/driver/depq.rb",
    "lib/unified-queues/single/driver/evented-queue.rb",
    "lib/unified-queues/single/driver/priority_queue.rb",
    "lib/unified-queues/single/driver/queue.rb",
    "test"
  ]
  s.homepage = "http://github.com/martinkozak/unified-queue"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Unifies many queue implementations under the single interface. Includes both single queue libraries and multiple queue libraries."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<abstract>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<hash-utils>, [">= 0.18.1"])
      s.add_runtime_dependency(%q<lookup-hash>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler2>, [">= 2.0.0"])
      s.add_development_dependency(%q<riot>, [">= 0.12.3"])
      s.add_development_dependency(%q<PriorityQueue>, [">= 0"])
      s.add_development_dependency(%q<algorithms>, [">= 0"])
      s.add_development_dependency(%q<depq>, [">= 0"])
    else
      s.add_dependency(%q<abstract>, [">= 1.0.0"])
      s.add_dependency(%q<hash-utils>, [">= 0.18.1"])
      s.add_dependency(%q<lookup-hash>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler2>, [">= 2.0.0"])
      s.add_dependency(%q<riot>, [">= 0.12.3"])
      s.add_dependency(%q<PriorityQueue>, [">= 0"])
      s.add_dependency(%q<algorithms>, [">= 0"])
      s.add_dependency(%q<depq>, [">= 0"])
    end
  else
    s.add_dependency(%q<abstract>, [">= 1.0.0"])
    s.add_dependency(%q<hash-utils>, [">= 0.18.1"])
    s.add_dependency(%q<lookup-hash>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler2>, [">= 2.0.0"])
    s.add_dependency(%q<riot>, [">= 0.12.3"])
    s.add_dependency(%q<PriorityQueue>, [">= 0"])
    s.add_dependency(%q<algorithms>, [">= 0"])
    s.add_dependency(%q<depq>, [">= 0"])
  end
end

